[codestyle]
indent_type='space' # 'tab' or 'space'
indent_width=2
template_file='~/repo/github.com/diohabara/competitive_programming/ac/template/my_template.cpp'
workspace_dir='~/repo/github.com/diohabara/competitive_programming/ac/'
lang='cpp' # Check README.md for the supported languages.
[postprocess]
exec_on_each_problem_dir='clang-format -i ./*.cpp'
exec_on_contest_dir='ln -s ../.vscode ./.vscode && code .'

[etc]
download_without_login=false
parallel_download=false
save_no_session_cache=false
in_example_format="in_{}.txt"
out_example_format="out_{}.txt"
